name: myfirst_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: print greeting
      run: echo "Hello, world" 
    - name: print end
      run: echo "Good-bye"